### ISSUE TITLE
Fix link cards

### ISSUE THREAD

**Issue by sumana2001** [Hackodisha/hackodisha-links#6]
<img width="1009" alt="Screenshot 2021-08-09 at 7 10 45 PM" src="https://user-images.githubusercontent.com/63084088/128715671-252e9a9f-0b5b-4df3-b247-1b267921e94d.png">

Make the width and height the same for all cards and the text should be placed at the bottom of the div so that the text is at the same level for each card. In case of confusion feel free to reply in the thread would be more than happy to explain.

**Comment by Mathewkutty** [comment]
Is Lord of the memes card image size intentionally changed?

<img width="1228" alt="Screenshot 2021-08-10 at 9 01 05 AM" src="https://user-images.githubusercontent.com/23608452/128804174-5ee3985c-7d04-4d6e-a8ef-f6bfc20d3821.png">

**Comment by sumana2001** [comment]
@Mathewkutty No it was not intentional. The screenshot looks great😍 But please make sure it is responsive for all screen sizes.

**Comment by Mathewkutty** [comment]
@sumana2001 I made a pr please check that
